<?php
/* @var $this Magneto_Debug_Block_Blocks */

$templateDirs = $this->getTemplateDirs();
$blocks = $this->getItems();
$layoutBlocks = $this->getLayoutBlocks();
?>

<?php $metrics = Mage::getModel('debug/metrics'); ?>
<?php foreach($blocks as $block ): ?>
    <?php if(array_key_exists('rendered_in', $block)): ?>
        <?php $metrics->addTime($block['rendered_in']); ?>
    <?php endif; ?>
<?php endforeach; ?>



<h4><?php echo $this->__('Template path') ?></h4>
<?php if( $templateDirs ): ?>
	<ol>
	<?php foreach( $templateDirs as $template ): ?>
		<li><?php echo $template; ?></li>
	</ol>
	<?php endforeach; ?>
<?php else: ?>
	<p>None</p>
<?php endif; ?>


<h4><?php echo $this->__('Rendered Blocks') ?></h4>
<p>List of all rendered blocks.</p>
<table class="debug-container">
	<thead>
		<tr>
			<th>#</th>
			<th><?php echo $this->__('name in layout') ?></th>
			<th><?php echo $this->__('block class') ?></th>
			<th><?php echo $this->__('template') ?></th>
            <th colspan="2"><?php echo $this->__('rendering in') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $blocks as $block ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td><?php echo $row ?></td>
                <td><?php echo $block['layout_name'] ?></td>
                <td>
                    <a href="http://localhost:8091/?message=<?php echo $this->getViewBlockUrl($block['class']) ?>:0"
                       onclick="var ajax = new XMLHttpRequest(); ajax.open('GET', this.href); ajax.send(null); return false;" ><?php echo $block['class'] ?></a>
                </td>
                <td>
                <?php if($block['template']):?>
                    <a href="http://localhost:8091/?message=<?php echo $this->getViewTemplateUrl($block['template']) ?>:0" class="toggletemplate"
                       onclick="var ajax = new XMLHttpRequest(); ajax.open('GET', this.href); ajax.send(null); return false;" ><?php echo $block['template'] ?></a>
                <?php endif; ?>
                </td>
                <td>
                    <?php echo $this->getRenderingTime($block) ?>
                </td>
                <td>
                    <?php if($this->getRenderingTime($block)): ?>
                        <?php  $level = $metrics->getLevel($block['rendered_in']); ?>
                        <div class="pastilles-level pastille-level<?php echo $level['level'] ?>" title="<?php echo $level['title']; ?>" ></div>
                    <?php endif; ?>
                </td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>

<h4><?php echo $this->__('Layout Blocks') ?></h4>
<p>List of all instantiated blocks, few of them might not be rendered.</p>
<table class="debug-container">
	<thead>
		<tr>
			<th>#</th>
			<th><?php echo $this->__('name in layout') ?></th>
			<th><?php echo $this->__('block class') ?></th>
			<th><?php echo $this->__('template') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $layoutBlocks as $block ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td><?php echo $row ?></td>
                <td><?php echo $block['layout_name'] ?></td>
                <td>
                    <a href="<?php echo $this->getViewBlockUrl($block['class']) ?>"
                       class="remoteCall"><?php echo $block['class'] ?></a>
                </td>
                <td>
                    <?php if($block['template']):?>
                    <a href="<?php echo $this->getViewTemplateUrl($block['template']) ?>"
                       class="remoteCall toggletemplate"><?php echo $block['template'] ?></a>
                    <?php endif; ?>
                </td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>
