<?php
$controller = Mage::registry('controller');
$request = $controller->getRequest();
$cookies = $_COOKIE;
$session = Mage::getSingleton('core/session');
?>
<h4><?php echo $this->__('Controller informations') ?></h4>
<span class="debug_request_path"><b><?php echo $this->__('Request Path') ?> :</b> <?php echo $request->getPathInfo() ?></span><br/>
<span class="debug_controller_module"><b><?php echo $this->__('Controller Module') ?> :</b> <?php echo $request->getControllerModule() ?></span>

<table class="debug-container debug-controller">
	<thead>
		<tr>
			<th><?php echo $request->getRouteName() ?></th>
			<th><?php echo $request->getControllerName() ?></th>
			<th><?php echo $request->getActionName() ?></th>
		</tr>
	</thead>
	<tbody>
		<tr class="djDebugOdd">
			<td><?php echo $this->__('Route Name') ?></td>
            <td><?php echo $this->__('Controller Name') ?></td>
            <td><?php echo $this->__('Action Name') ?></td>
        </tr>
	</tbody>
</table>

<h4><?php echo $this->__('COOKIES Variables') ?></h4>
<?php if( $cookies ): ?>
	<table class="debug-container">
		<colgroup>
			<col style="width:20%"/>
			<col/>
		</colgroup>
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach( $cookies as $key=>$value ): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td><?php echo htmlspecialchars($value) ?></td>
				</tr>
				<?php $row++; ?>
			<?php endforeach ?>
		</tbody>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No COOKIE data") ?></p>
<?php endif ?>

<h4><?php echo $this->__('SESSION Variables') ?></h4>
<?php if( count($_SESSION)): ?>
	<table class="debug-container">
		<colgroup>
			<col style="width:20%"/>
			<col/>
		</colgroup>
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<?php foreach( $_SESSION as $namespace => $data): ?>
		<tbody>
			<tr><th colspan="2" class="debug-container-title-module"><?php echo $namespace ?></th></tr>
			<?php $row = 0; ?>
			<?php foreach( $data as $key => $value ): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td>
					<?php if( is_array($value) ): ?>
						<?php foreach ($value as $key => $_value): ?>
						<?php echo $key.' => '.$this->escapeHtml(json_encode($_value)); ?><br/>
						<?php endforeach; ?>
					<?php elseif( is_object($value)): ?>
						<?php echo get_class($value) ?>
					<?php else: ?>
						<?php echo htmlspecialchars($value) ?>
					<?php endif ?>
					</td>
				</tr>
				<?php $row++; ?>
			<?php endforeach; ?>
		</tbody>
		<?php endforeach; ?>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No SESSION data") ?></p>
<?php endif ?>

<h4><?php echo $this->__("GET Variables") ?></h4>
<?php if( $_GET ):?>
	<table class="debug-container">
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach ($_GET as $key=>$value): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td><?php echo htmlspecialchars(var_export($value, true)) ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No GET data") ?></p>
<?php endif ?>

<h4><?php echo $this->__("POST Variables") ?></h4>
<?php if( $_POST ):?>
	<table class="debug-container">
		<thead>
			<tr>
				<th><?php echo $this->__("Variable") ?></th>
				<th><?php echo $this->__("Value") ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $row = 0; ?>
			<?php foreach ($_POST as $key=>$value): ?>
				<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
					<td><?php echo htmlspecialchars($key) ?></td>
					<td><?php echo htmlspecialchars(var_export($value, true)) ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php else: ?>
	<p><?php echo $this->__("No POST data") ?></p>
<?php endif ?>
