<?php $events = $this->getEvents(); ?>
<h4><?php echo $this->__("Events/Observers") ?></h4>
<table>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach($events as $event ): ?>
            <tr class="<?php echo (($row % 2)?'djDebugOdd':'djDebugEven') ?>">
                <td><b><?php echo $event['event'] ?></b>
                    <?php if(isset($event['observers'])): ?>
                        <ul>
                            <?php foreach ( $event['observers'] as $observer) : ?>
                                <li>|-> <i><?php echo $observer ?><i></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </td>
            </tr>
            <?php $row++; ?>
        <?php endforeach; ?>
	</tbody>
</table>