<?php $events = $this->getEvents(); ?>

<?php $metrics = Mage::getModel('debug/metrics'); ?>
<?php foreach($events as $event ): ?>
    <?php if(isset($event['observers'])): ?>
        <?php foreach ( $event['observers'] as $observer) : ?>
            <?php $metrics->addTime($observer['time']); ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>


<h4><?php echo $this->__("Events/Observers") ?></h4>
<table class="debug-container">
    <thead>
        <tr>
            <th><?php echo $this->__('DISPATCH EVENT'); ?></th>
            <th><?php echo $this->__('OBSERVER'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach($events as $event ): ?>
            <tr class="<?php echo (($row % 2)?'djDebugOdd':'djDebugEven') ?>">
                <td><?php echo $event['event'] ?></td>
                <td>
                    <?php if(isset($event['observers'])): ?>
                        <table class="debug-observers">
                            <?php foreach ( $event['observers'] as $observer) : ?>
                                <tr>
                                    <td class="col-left-observer"><i><?php echo $observer['title'] ?><i></td>
                                    <td class="observer-col-time"><?php echo round($observer['time'],5); ?></td>
                                    <?php  $level = $metrics->getLevel($observer['time']); ?>
                                    <td><div class="pastilles-level pastille-level<?php echo $level['level'] ?>" title="<?php echo $level['title']; ?>" ></div></td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    <?php endif; ?>
                </td>
            </tr>
            <?php $row++; ?>
        <?php endforeach; ?>
	</tbody>
</table>