<?php
/* @var $this Magneto_Debug_Block_Layout */
$layout =  Mage::getSingleton('core/layout');
$layoutHandles = Mage::getSingleton('core/layout')->getUpdate()->getHandles();
$layoutUpdates = Mage::getSingleton('core/layout')->getUpdate()->asArray();

/* @var $designPackage Mage_Core_Model_Design_Package */
$designPackage = Mage::getSingleton('core/design_package');
?>

<h4><?php echo $this->__('Package information') ?></h4>
<table class="debug-container debug-layout">
    <thead>
    <tr>
        <th><?php echo $designPackage->getArea() ?></th>
        <th><?php echo $designPackage->getPackageName() ?></th>
        <th><?php echo $designPackage->getTheme('template') ?></th>
    </tr>
    </thead>
    <tbody>
        <tr class="djDebugOdd">
            <td><?php echo $this->__('Design Area') ?></td>
            <td><?php echo $this->__('Package Name') ?></td>
            <td><?php echo $this->__('Template Theme') ?></td>
        </tr>
    </tbody>
</table>

<h4><?php echo $this->__('Handles for this request'); echo "(" . count($layoutHandles) . ")" ?></h4>
<table class="debug-container">
	<thead>
		<tr>
			<th><?php echo $this->__('Handle') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $layoutHandles as $item ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td><?php echo $item ?></td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>

<dl>
    <dt><strong>Page Layout</strong></dt>
    <dd>
		<div class="djTemplateShowContextDiv"><a class="djTemplateShowContext"><span class="toggleArrow">&#x25B6;</span>View Page Layout</a></div>
        <div class="djTemplateHideContextDiv" style="display:none;">
            <code><?php echo htmlspecialchars($layout->getNode()->asXML()) ?></code>
        </div>
	</dd>
</dl>

<h4><?php echo $this->__('Layout updates') ?> (<?php echo count($layoutUpdates); ?>)</h4>
<table class="debug-container">
	<thead>
		<tr>
			<th><?php echo $this->__('#'); ?></th>
			<th><?php echo $this->__('Update') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $layoutUpdates as $item ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
			<td><?php echo $row ?>.</td>
			<td class="syntax">
				<code><?php echo htmlspecialchars($item) ?></code>
				</td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>

