<?php $logs = $this->getLogs(); ?>

<?php foreach ($logs as $file => $logs): ?>
    <h4><?php echo $file ?></h4>
    <?php $row = 0; ?>
    <table class="debug-logs">
        <tbody>
            <?php foreach ($logs as $content) : ?>
                <tr class="<?php echo(($row % 2) ? 'djDebugOdd' : 'djDebugEven') ?>">
                    <td>
                        <?php echo $content ?>
                    </td>
                </tr>
                <?php $row++; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endforeach; ?>
