<?php
/* @var $this Magneto_Debug_Block_Models */

$items = $this->getItems();
Mage::helper('debug')->sortModelsByOccurrences($items);
$collections = $this->getCollections();
$queries = $this->getQueries();
?>

<h4><?php echo $this->__('MODELS') ?></h4>
<table class="debug-container">
	<thead>
		<tr>
			<th><?php echo $this->__('Resource Name') ?></th>
			<th><?php echo $this->__('Model Class') ?></th>
			<th><?php echo $this->__('Times Instantiated') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $items as $item ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
				<td><?php echo $item['resource_name'] ?></td>
				<td><?php echo $item['class'] ?></td>
				<td><?php echo $item['occurrences'] ?></td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>
<h4><?php echo $this->__('QUERIES') ?></h4>
<?php if( $queries ): ?>

    <?php $metrics = Mage::getModel('debug/metrics'); ?>
    <?php foreach( $queries as $item ): ?>
        <?php $metrics->addTime($item->getElapsedSecs()); ?>
    <?php endforeach; ?>
    <p><a class="toggleTemplate" href="<?php echo Mage::getUrl('debug/index/toggleSqlProfiler') ?>">Disable SQL Profiler</a></p>
    <table class="debug-container">
        <thead>
        <tr>
            <th><?php echo $this->__('Query') ?></th>
            <th colspan="2"><?php echo $this->__('Time') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php $row = 0; ?>
        <?php foreach( $queries as $item ): ?>
            <tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
                <td class="syntax">
                    <div class="djDebugSqlWrap">
                        <div class="djDebugSql"><?php echo $item->getQuery() ?>
                            <?php if( count($item->getQueryParams()) ): ?>
                                <br/><strong>Params:</strong> <?php echo implode(', ', $item->getQueryParams()); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </td>
                <td>
                    <div class=""><?php echo sprintf("%.4f", $item->getElapsedSecs()) ?>&nbsp;s</div>
                </td>
                <td>
                    <?php  $level = $metrics->getLevel($item->getElapsedSecs()); ?>
                    <div class="pastilles-level pastille-level<?php echo $level['level'] ?>" title="<?php echo $level['title']; ?>" ></div>
                </td>
            </tr>
            <?php $row++; ?>
        <?php endforeach ?>
        </tbody>
    </table>
<?php else: ?>
    <p>SQL Profiler is not enabled. <a class="toggleTemplate" href="<?php echo Mage::getUrl('debug/index/toggleSqlProfiler') ?>">Enable SQL Profiler</a></p>
<?php endif; ?>

<h4><?php echo $this->__('COLLECTIONS') ?></h4>
<table class="debug-container">
	<thead>
		<tr>
			<th><?php echo $this->__('Type') ?></th>
			<th><?php echo $this->__('Class') ?></th>
			<th><?php echo $this->__('SQL') ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $row = 0; ?>
		<?php foreach( $collections as $item ): ?>
			<tr class="<?php echo ( ($row % 2 ? 'djDebugOdd' : 'djDebugEven')) ?>">
				<td><?php echo $item['type'] ?></td>
				<td><?php echo $item['class'] ?></td>
				<td><?php echo $item['sql'] ?></td>
			</tr>
			<?php $row++; ?>
		<?php endforeach ?>
	</tbody>
</table>

